%YAML:1.0
---
uav_name: "kun0"
Origin_location: "imu"

front_camera:
  serial_no: "037322251575"
  color_camera:
    name: "D455_COLOR_CAM"
    image_width: 640
    image_height: 480
    fx: 319.9988245765257
    fy: 319.9988245765257
    cx: 320.5
    cy: 240.5
    distortion_model: "plumb_bob"
    D: [-0.0, 0.0, 0.0, -0.0, -0.0]
    T_imu_camColor: [1, 0, 0, 0.12,
                     0, 1, 0, 0.1,
                     0, 0, 1, 0.0,
                     0, 0, 0, 1]

  ir_camera:
    name: "D455_IR_CAM"
    IR_1:
      image_width: 640
      image_height: 480
      fx: 389.8620910644531
      fy: 389.8620910644531
      cx: 315.6733703613281
      cy: 240.7991943359375
      distortion_model: "plumb_bob"
      D: [0.0, 0.0, 0.0, 0.0, 0.0]
      # ENU坐标系 front x left y up z
      T_camColor_camIR1:  [ 1, 0, 0, 0,
                            0, 1, 0, 0.0591,
                            0, 0, 1, 0,
                            0.000, 0.000, 0.000, 1.000 ]
    IR_2:
      image_width: 640
      image_height: 480
      fx: 389.8620910644531
      fy: 389.8620910644531
      cx: 315.6733703613281
      cy: 240.7991943359375
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # ENU坐标系 front x left y up z
      T_camIR1_camIR2:  [ 1, 0, 0, 0,
                        0, 1, 0, -0.0952,
                        0, 0, 1, 0,
                        0, 0, 0, 1 ]


side_camera:
  serial_no: "216322074755"
  color_camera:
    name: "D435_COLOR_CAM"
    image_width: 640
    image_height: 480
    fx: 605.455
    fy: 604.953
    cx: 328.852
    cy: 252.618
    distortion_model: "plumb_bob"
    D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
    T_imu_camColor: [0, 1, 0, 0.0125,
                 -1, 0, 0, -0.07,
                 0, 0, 1, 0.00,
                 0, 0, 0, 1]

  ir_camera:
    name: "D435_IR_CAM"
    IR_1:
      image_width: 640
      image_height: 480
      fx: 386.466 # 386.466
      fy: 386.466 # 386.466
      cx: 323.427
      cy: 234.104
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # ENU坐标系 front x left y up z
      T_camColor_camIR1:  [ 1, 0, 0, 0,
                            0, 1, 0, -0.0149,
                            0, 0, 1, 0,
                            0.000, 0.000, 0.000, 1.000 ]
    IR_2:
      image_width: 640
      image_height: 480
      fx: 386.466
      fy: 386.466
      cx: 323.427
      cy: 234.104
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # ENU坐标系 front x left y up z
      T_camIR1_camIR2:  [1, 0, 0, 0,
                         0, 1, 0, -0.0499,
                         0, 0, 1, 0,
                         0, 0, 0, 1]

#image坐标系转为enu的cam坐标系 需要左乘 T_cam_image
T_cam_image: [0, 0, 1, 0,
              -1, 0, 0, 0,
              0, -1, 0, 0,
              0, 0, 0, 1]

T_imu_t265: [1, 0, 0, 0.0,
             0, 1, 0, 0.0,
             0, 0, 1, 0.0]

imu:
  imu_name: "Xsens-MTi-630"

Marker:
  marker_type: "xyz-stick-top"
  T_imu_marker: [1, 0, 0, 0,
                 0, 1, 0, -0.0375,
                 0, 0, 1, 0.07,
                 0, 0, 0, 1]

IRLandmark:
  layout_name: "6-point-2-rows"
  number: 6
  layout: [ 0.000, 0.0, 0.0,
            100.0, 0.0, 0.0,
            176.0, 0.0, 0.0,
            276.5, 0.0, 0.0,
            0.000, 0.0, -79.0,
            176.0, 0.0, -79.0]
  T_imu_IRLandmark: [ 1, 0, 0, -0.14,
                      0, 1, 0, -0.14,
                      0, 0, 1, -0.06,
                      0, 0, 0, 1]