%YAML:1.0
---
uav_name: "kun0"
Origin_location: "imu"

front_camera:
  serial_no: "037322251575"
  color_camera:
    name: "D455_COLOR_CAM"
    image_width: 640
    image_height: 480
    fx: 381.7646789550781
    fy: 380.9313049316406
    cx: 317.666748046875
    cy: 239.6370849609375
    distortion_model: "plumb_bob"
    D: [-0.0537783, 0.0611120, 0.0004679, -0.0003762, -0.0190100]
    T_imu_camColor: [1, 0, 0, 0.045,
                     0, 1, 0, -0.0125,
                     0, 0, 1, 0.0,
                     0, 0, 0, 1]

  ir_camera:
    name: "D455_IR_CAM"
    IR_1:
      image_width: 640
      image_height: 480
      fx: 389.8620910644531
      fy: 389.8620910644531
      cx: 315.6733703613281
      cy: 240.7991943359375
      distortion_model: "plumb_bob"
      D: [0.0, 0.0, 0.0, 0.0, 0.0]
      # camera图像坐标系, right x, down y, front z
      T_camColor_camIR1:  [ 0.999, 0.003, -0.003, -0.0591,
                            -0.003, 0.999, 0.000, -0.0002,
                            0.003, 0.000, 0.999, 0.0003,
                            0.000, 0.000, 0.000, 1.000 ]
    IR_2:
      image_width: 640
      image_height: 480
      fx: 389.8620910644531
      fy: 389.8620910644531
      cx: 315.6733703613281
      cy: 240.7991943359375
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # camera图像坐标系, right x, down y, front z
      T_camIR1_camIR2:  [ 1, 0, 0, 0.0952,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, 0, 1 ]


side_camera:
  serial_no: "102422072335"
  color_camera:
    name: "D435_COLOR_CAM"
    image_width: 640
    image_height: 480
    fx: 606.082
    fy: 604.795
    cx: 322.827
    cy: 244.656
    distortion_model: "plumb_bob"
    D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
    T_imu_camColor: [0, 1, 0, 0.0125,
                 -1, 0, 0, -0.07,
                 0, 0, 1, 0.00,
                 0, 0, 0, 1]

  ir_camera:
    name: "D435_IR_CAM"
    IR_1:
      image_width: 640
      image_height: 480
      fx: 381.866
      fy: 381.866
      cx: 316.761
      cy: 239.285
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # camera图像坐标系, right x, down y, front z
      T_camColor_camIR1:  [ 0.999, 0.0027, -0.0027, 0.0149,
                            -0.0027, 0.999, -0.0039, -0.0002,
                            0.0027, 0.0039, 0.999, -0.0002,
                            0.000, 0.000, 0.000, 1.000 ]
    IR_2:
      image_width: 640
      image_height: 480
      fx: 381.866
      fy: 381.866
      cx: 316.760
      cy: 239.284
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # camera图像坐标系, right x, down y, front z
      T_camIR1_camIR2:  [1, 0, 0, 0.0499,
                         0, 1, 0, 0,
                         0, 0, 1, 0,
                         0, 0, 0, 1]

#image坐标系转为enu的cam坐标系 需要左乘 T_cam_image
T_cam_image: [0, 0, 1, 0,
              -1, 0, 0, 0,
              0, -1, 0, 0,
              0, 0, 0, 1]

T_imu_t265: [1, 0, 0, 0.14,
             0, 1, 0, 0.0,
             0, 0, 1, -0.13]

imu:
  imu_name: "Xsens-MTi-630"

Marker:
  marker_type: "xyz-stick-top"
  T_imu_marker: [1, 0, 0, 0,
                 0, 1, 0, -0.0375,
                 0, 0, 1, 0.07,
                 0, 0, 0, 1]