%YAML:1.0
---
uav_name: "kun1"
Origin_location: "imu"

front_camera:
  serial_no: "037522250849"
  color_camera:
    name: "D455_COLOR_CAM"
    image_width: 640
    image_height: 480
    fx: 383.949
    fy: 383.567
    cx: 316.075
    cy: 245.676
    distortion_model: "plumb_bob"
    D: [-0.0547429, 0.0643438, 0.000231644, 0.00011313,-0.0206193]
    T_imu_camColor: [1, 0, 0, 0.045,
                 0, 1, 0, 0.025,
                 0, 0, 1, -0.07,
                 0, 0, 0, 1]

  ir_camera:
    name: "D455_IR_CAM"
    IR_1:
      image_width: 640
      image_height: 480
      fx: 389.767
      fy: 389.767
      cx: 314.743
      cy: 240.199
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      T_camColor_camIR1: [ 0.9999, 0.0006, 0.0036, -0.0589626,
                           -0.0006, 0.9999, 0.0057, 0.000115235,
                           -0.0036, -0.0057, 0.9999, 0.000396183,
                          0, 0, 0, 1 ]
    IR_2:
      image_width: 640
      image_height: 480
      fx: 389.767
      fy: 389.767
      cx: 314.743
      cy: 240.199
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      T_camIR1_camIR2: [1, 0, 0, 0.0949,
                        0, 1, 0, 0.0,
                        0, 0, 1, 0.0,
                        0, 0, 0, 1 ]

side_camera:
  serial_no: "044122070464"
  color_camera:
    name: "D435_COLOR_CAM"
    image_width: 640
    image_height: 480
    fx: 607.563
    fy: 608.192
    cx: 328.089
    cy: 232.844
    distortion_model: "plumb_bob"
    D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
    # ENU坐标系 front x left y up z
    T_imu_camColor: [0, -1, 0, -0.06,
                 1, 0, 0, 0.07,
                 0, 0, 1, 0.0,
                 0, 0, 0, 1]

  ir_camera:
    name: "D435_IR_CAM"
    IR_1:
      image_width: 640
      image_height: 480
      fx: 382.265
      fy: 382.265
      cx: 323.955
      cy: 239.286
      distortion_model: "plumb_bob"
      D: [0.0, 0.0, 0.0, 0.0, 0.0]
      # camera图像坐标系, right x, down y, front z
      T_camColor_camIR1:  [ 0.999, -0.0087, -0.0004, 0.0147,
                            0.0087, 0.999, -0.0059, -0.0003,
                            0.0004, 0.0059, 0.999, -0.0004,
                            0.000, 0.000, 0.000, 1.000 ]
    IR_2:
      image_width: 640
      image_height: 480
      fx: 382.265
      fy: 382.265
      cx: 323.955
      cy: 239.286
      distortion_model: "plumb_bob"
      D: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
      # camera图像坐标系, right x, down y, front z
      T_camIR1_camIR2:  [1, 0, 0, 0.0499,
                         0, 1, 0, 0,
                         0, 0, 1, 0,
                         0, 0, 0, 1]

#image坐标系转为enu的cam坐标系 需要左乘 T_cam_image
T_cam_image: [0, 0, 1, 0,
             -1, 0, 0, 0,
             0, -1, 0, 0,
             0, 0, 0, 1]

T_imu_t265: [1, 0, 0, 0.14,
             0, 1, 0, 0.0,
             0, 0, 1, -0.13]

imu:
  imu_name: "Xsens-MTi-630"

Marker:
  marker_type: "xyz-stick-top"
  T_imu_marker: [1, 0, 0, 0,
                 0, 1, 0, -0.0375,
                 0, 0, 1, 0.07,
                 0, 0, 0, 1]